lr: 1.0e-3
lr_end: 1.0e-5
n_epochs: 2000
grad_norm: 0
eval_epochs: 50
batch_size: 16
cuda: true
k: 64
loss_f: smc
resample: systematic # multinomial or none
observation_likelihood: Poisson # observation likelihood
t_forward: ${dataset.t_forward}
run_eval: false
